### PR TITLE
Updating to version 0.3.1

### PR DESCRIPTION
**Pull request by dfm**

### CODE REVIEW

**Comment by scopatz** [comment]
LGTM!

**Comment by scopatz** [comment]
Looks like windows failed to build @dfm

**Comment by dfm** [comment]
I saw that. Do you understand the error messages at all? I can't really work out which step is failing. I do test on appveyor and everything builds fine so I suspect that it is something on the conda-forge side, but I never quite know what I'm doing with Windows :-)

**Comment by scopatz** [comment]
Hmm I don't know.... Let's try rerendering

@conda-forge-admin, please rerender

**Comment by scopatz** [comment]
Ahh great, that seemed to fix the windows build!

**Comment by dfm** [comment]
Great - thanks!

**Pull request merged**
