### PR TITLE
Update to v0.3.0

### PR DESCRIPTION
**Pull request by dfm**
I've just released a new version of george so I wanted to update that here as well. I re-rendered the feedstock, updated the version of george, and added myself as a maintainer. If you don't want me as a maintainer for some reason, I'm happy to roll back that commit 😄. It should build on Windows now, but if there are any issues, I'll look into them. Thanks!

### CODE REVIEW

**Comment by dfm** [comment]
Looks like we probably need to do something else to enable the Appveyor webhook since this feedstock was originally created without Windows support. I'm not sure how to do that, but I'll look into it. If anyone else sees this and knows, please let me know. Thanks!

**Comment by scopatz** [comment]
Thanks @dfm! This looks great, and happy to have you as a maintainer! Just waiting for the CI to pass.

**Comment by dfm** [comment]
OK. I'm working out a few issues here, but I think I'm close to getting this to work!

**Comment by scopatz** [comment]
Sounds good. Just ping the conversation here when you think it is ready, and I'll merge.

**Comment by dfm** [comment]
Will do. Thanks!

**Comment by dfm** [comment]
@scopatz: The Mac build on Travis finally finished and it looks like everything is good from this side. I'd say it's ready to merge unless you spot any issues!

**Comment by scopatz** [comment]
Looks great! Thanks!

**Pull request merged**
